/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (1, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499736/Standard_Network_Engineer', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572314/Network_Engineer_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:17.563' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (2, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/624040/Standard_Software_Developer.pd', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578776/Software_Developer.pdf', CAST(N'2017-10-10T14:36:17.817' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (5, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448907/ELECTROTECHNICAL_Installation_Electrician__Maintenance_Electrician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/459797/Electrotechnical.pf', CAST(N'2017-10-10T14:36:18.047' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (6, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448908/ENERGY___UTILITIES_Power_Network_Craftsperson.pd', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574230/Power_Network_Craftsperson_V3.pdf', CAST(N'2017-10-10T14:36:18.720' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (7, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598463/Financial_Services_Relationship_Mgr_Banking.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528460/Relationship_Manager_Assessment_Plan.df', CAST(N'2017-10-10T14:36:19.540' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (8, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/367332/Financial_Services_Network_Administrator_standard.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/367333/AP_-_Financial_Services_Administrator_Assessment_Plan.ashx.pdf', CAST(N'2017-10-10T14:36:19.770' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (9, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370657/AUTOMOTIVE_Control_-_Technical_Support_Engineer_standards.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370658/AP_-_Control-Technical_Support_Engineer_Automotive_Trailblazer_Assessment_Strategy.ashx.pdf', CAST(N'2017-10-10T14:36:19.990' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (10, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370660/AUTOMOTIVE_Electrical_-_Electronic_Technical_Support_Engineer_standard.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370662/AP_-_Electrical_Electronic_Technical_Support_Engineer_Automotive_Trailblazer_Assessment_Strategy.ashx.pdf', CAST(N'2017-10-10T14:36:20.233' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (11, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370664/AUTOMOTIVE_Manufacturing_Engineer_standard.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/370665/AP_-Manufacturing_Engineer_Assessment_Plan.ashx.pdf', CAST(N'2017-10-10T14:36:20.450' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (12, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/376482/AUTOMOTIVE_Product_Design_and_Development_Engineer.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/376483/AP_-_Product_Design_and_Development_Engineer_Automotive_Trailblazer_Assessment_Strategy.ashx.pdf', CAST(N'2017-10-10T14:36:20.663' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (14, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448943/LIFE_AND_INDUSTRIAL_SCIENCES_Laboratory_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648984/ST0248_Laboratory_Technician_Assessment_Plan__29ept17.pdf', CAST(N'2017-10-10T14:36:21.327' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (15, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448968/LIFE_AND_INDUSTRIAL_SCIENCES_Science_Manufacturing_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648982/ST0250_Science_Manufacturing_Technician__Assessment_Plan_29Sept17__003_.pdf', CAST(N'2017-10-10T14:36:22.437' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (16, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555632/Food_and_Drink_Maintenance_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555633/Food_and_Drink__Maintenance_Engineer_Assessment_Plan_V2.pdf', CAST(N'2017-10-10T14:36:22.660' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (17, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411723/ACTUARIAL_-_Actuarial_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416804/Actuarial_Technician_-_Assessment_Plan_Final.pdf', CAST(N'2017-10-10T14:36:23.487' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (18, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372168/DENTAL_HEALTH_Dental_Technician.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416794/Dental_Technician_-_Assessment_Plan_Final.pdf', CAST(N'2017-10-10T14:36:23.707' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (19, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372181/DENTAL_HEALTH_Dental_Laboratory_Assistant.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416796/Dental_Lab_Assistant_-_Assessment_Plan_Final.pdf', CAST(N'2017-10-10T14:36:23.930' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (20, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592663/Dental_Practice_Manager_Standard_-_Feb_2017.', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592664/Dental_Practice_Manager_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:24.187' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (21, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372241/GOLF_GREENKEEPING_HORTICULTURE_Golf_Greenkeeper.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/542482/Assessment_plan_-_Greenkeepers_July_2016.pdf', CAST(N'2017-10-10T14:36:25.457' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (22, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/414194/NEWSPAPER__BROADCAST_MEDIA_-_Junior_Journalist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416547/Junior_Journalist_Assessment_Plan_Final.pdf', CAST(N'2017-10-10T14:36:26.623' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (23, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372239/PROPERTY_SERVICES_Property_Maintenance_Operative.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416546/Assessment_Plan_-_Property_Maintenance_Operative_Final_Version.', CAST(N'2017-10-10T14:36:27.527' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (24, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372618/RAIL_DESIGN_Railway_Engineering_Design_Technician.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416550/Railway_Engineering_Design_Technician_Apprenticeship_-_Assessment_Strate....pdf', CAST(N'2017-10-10T14:36:28.570' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (25, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411741/DIGITAL_INDUSTRIES_-_Digital___Technology_Solutions_Professional.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416553/Degree_Apprenticeship_in_Digital_Technology_Solutions__Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:28.807' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (26, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455239/ENERGY___UTILITIES_Dual_Fuel_Smart_Meter_Installer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574275/Smart_Meter_Installer_V2__005_.pdf', CAST(N'2017-10-10T14:36:29.643' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (27, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/451811/Water_Process_Technician_-_Level_3.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574236/Water_Process_Technician_V2.pdf', CAST(N'2017-10-10T14:36:31.070' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (28, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598442/FS_Cust_Adviser_Level_2_standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598441/FS_Cust_Advsr_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:31.297' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (29, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411830/FINANCIAL_SERVICES_-_Investment_Operations_Administrator.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528454/Inv_Ops_Administrator_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:31.520' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (30, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411850/FINANCIAL_SERVICES_-_Investment_Operations_Specialist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528449/Inv_Ops_Specialist_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:31.743' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (31, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598458/Snr_FS_Cust_Svce_Adviser_Level_3_standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528461/Snr_FS_Cust_Advsr_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:31.967' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (32, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448937/FINANCIAL_SERVICES_Workplace_Pensions_Administrator_or_Consultant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528447/WP_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:32.810' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (33, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448912/FINANCIAL_SERVICES_Investment_Operations_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528448/Inv_Ops_Technician_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:33.047' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (34, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411724/MARITIME_-_Able_Seafarer__Deck_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/456750/Able_Sea_Farer.pdf', CAST(N'2017-10-10T14:36:33.273' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (35, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411708/NUCLEAR_-_Nuclear_Welding_Inspection_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/456752/NWIT.pdf', CAST(N'2017-10-10T14:36:33.490' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (36, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384255/PUBLIC_SERVICE_-_Operational_Delivery_Officer_standard-_Final_081214.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/456758/PublicServiceOperationalDeliveryAssessmentPlan_-_Ready.pdf', CAST(N'2017-10-10T14:36:33.770' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (37, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603417/Aerospace_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603876/L6_Aerospace_Engineer_End_Point_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:34.023' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (38, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603418/Aero_Software_Development_Eng.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603875/L6_Aerospace_Software_Development_Engineer_End_Point_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:34.253' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (39, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372127/Conveyancing_Technician_Apprenticeship_Standard_final.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546977/Conveyancing_Technician_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:35.303' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (40, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372137/Licensed_Conveyancer_Apprenticeship_Standard_Final.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546980/Licensed_Conveyancer_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:35.567' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (41, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372552/LAW_Chartered_Legal_Executive.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/458227/CLE_Assessment_plan.pdf', CAST(N'2017-10-10T14:36:35.790' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (42, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372474/LAW_Paralegal.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/458228/Paralegal_apprenticeship_standard_assessment_plan.pdf', CAST(N'2017-10-10T14:36:36.010' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (43, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448939/LAW_Solicitor.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/458232/Solicitor_Apprenticeship_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:36.913' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (44, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411712/LIFE___INDUSTRIAL_SCIENCES_-_Laboratory_Scientist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648983/ST0248_LaboratoryScientist__Assessment_Plan__29Sept_17__002_.pdf', CAST(N'2017-10-10T14:36:37.137' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (45, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384224/LIFE_SCIENCES_AND_INDUSTRIAL_SCIENCES_-_Science_Industry_Maintenance_Technician_-_Final_081214.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648985/ST0249_Science_Industry_Maintenance_Technician_29.09.17.pdf', CAST(N'2017-10-10T14:36:37.370' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (46, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411707/NUCLEAR_-_Nuclear_Health_Physics_Monitor.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572129/Nuclear_Health_Physics_Monitor_assessment_plan.pdf', CAST(N'2017-10-10T14:36:37.597' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (47, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598676/Nuclear_Scientist_and_Nuclear_Engineer_Integrated_Degree_Apprenticeship_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/586622/Nuclear_Scientist_and_Nuclear_Engineer_Integrated_Degree_Apprenticeship_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:37.823' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (48, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411726/FINANCIAL_SERVICES_-_Paraplanner.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/459825/Assessment_plan_Paraplanner.pdf', CAST(N'2017-10-10T14:36:38.043' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (49, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411703/REFRIGERATION_AIR_CONDITIONING_AND_HEAT_PUMP__RACHP__-_Refrigeration_Air_Conditioning_and_Heat_Pump_Engineering_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/649207/ST0322_Refrigeration_Air_Conditioning_and_Heat_Pump_Engineering_Technician_for_Publishing_03.1017__1_.pdf', CAST(N'2017-10-10T14:36:38.310' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (50, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/525956/Chartered_Surveyor_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/525957/Chartered_Surveyor_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:38.617' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (51, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/525958/Surveying_Technician_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/525959/Surveying_Technician_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:38.830' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (52, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448905/DEFENCE_Systems_Engineering_Master_Level.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/460423/Systems_Engineering_Masters.pdf', CAST(N'2017-10-10T14:36:39.790' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (53, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/451813/Utilities_Engineering_Technician_-_Level_3.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574232/Utilities_Engineering_Technician_V2__002_.pdf', CAST(N'2017-10-10T14:36:40.010' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (54, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553773/Butcher_Version_2.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553774/ButcherL2EndPointAssessmentPlan.pdf', CAST(N'2017-10-10T14:36:40.827' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (55, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/641867/Chartered_Manager_Degree_Apprenticeship_V2.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605260/Chartered_Manager_Degree_Apprenticeship_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:41.600' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (57, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411792/ENERGY___UTILITIES_-_Gas_Network_Craftsperson.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574258/Gas_Network_Craftsperson_V2.pdf', CAST(N'2017-10-10T14:36:42.517' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (58, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411797/ENERGY___UTLITIES__-_Gas_Network_Team_Leader.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574237/Gas_Team_leader.pdf', CAST(N'2017-10-10T14:36:43.720' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (59, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/470805/AUTOMOTIVE_RETAIL_Motor_Vehicle_Service_and_Maintenance_Technician__Light_Vehicle_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514632/Trailblazer_retail_automotive_LVA.pdf', CAST(N'2017-10-10T14:36:43.957' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (60, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372245/INSURANCE_Insurance_Practitioner.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/472383/Insurance_Practitioner.pdf', CAST(N'2017-10-10T14:36:45.067' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (61, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411720/DENTAL_HEALTH_-_Dental_Nurse.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/476636/Dental_Nursing_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:45.300' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (62, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/454974/FINANCIAL_SERVICES_Mortgage_Adviser.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/478124/Mortgage_Adviser_AP.pdf', CAST(N'2017-10-10T14:36:46.300' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (63, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455140/INSURANCE__Insurance_Professional.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/614650/INSURANCE_PROFESSIONAL_AP.pdf', CAST(N'2017-10-10T14:36:47.213' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (64, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455082/HOUSING_Housing_Property_Management_Assistant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/480325/L2_Housing_and_Property_Management_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:47.453' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (65, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416895/HOUSING_-_Housing_Management_-_Final.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416540/Housing_Property_Management-_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:47.693' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (66, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/456535/HOUSING_-_Senior_Housing_or_Property_Management.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/480324/L4_Housing_and_Property_Management_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:48.630' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (67, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/485264/Non-Destructive_Testing_Engineering_Technician_Standard_-_Version_2_FINAL_26_Nov.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/480732/NDT_Engineering_Technician_Assesment_Plan.pdf', CAST(N'2017-10-10T14:36:49.743' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (68, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455240/ENERGY_MANAGEMENT_Junior_Energy_Manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/481394/JEM.pdf', CAST(N'2017-10-10T14:36:50.033' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (69, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578711/Land-_based_Service_Engineering.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/488454/Land-based_Service_Engineering__LBSE__Service_Engineer_L2.pdf', CAST(N'2017-10-10T14:36:50.390' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (70, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578716/Land-based_Service_Engineering_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/488456/Land-based_Service_Engineering__LBSE__Technician_L3.pdf', CAST(N'2017-10-10T14:36:50.747' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (71, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455150/LIVE_EVENTS_Live_Event_Rigger.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/488431/Live_Event_Rigger_Assessment_Plan_aj.pdf', CAST(N'2017-10-10T14:36:51.477' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (72, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455227/BESPOKE_TAILORING__Bespoke_Tailor_and_Cutter.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/497470/Bespoke_Tailoring_Final.pdf', CAST(N'2017-10-10T14:36:52.753' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (73, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/645443/Public_Sector_Commercial_Professional_Apprenticeship_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/645445/Apprenticeship_Assessment_Plan_-_Public_Sector_Commercial_Final_Jan_16_p....pdf', CAST(N'2017-10-10T14:36:53.073' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (74, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499754/Gas_engineering_standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574273/Gas_engineering_assessment_plan_V2.pdf', CAST(N'2017-10-10T14:36:53.413' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (75, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499741/Outside_Broadcasting_Engineer_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/502091/OB_Engineer_Assessment_Plan-Jan16-v1.pdf', CAST(N'2017-10-10T14:36:54.407' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (76, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411727/BOATBUILDING_-_Boatbuilder.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/503621/Boatbuilding_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:54.693' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (77, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/454965/FINANCIAL_SERVICES_Credit_Controller_Collector.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514590/Credit_Management_Collector_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:55.057' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (78, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/510136/Standard_Digital_Marketer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572320/Digital_Marketer_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:55.420' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (79, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/510119/Standard_Cyber_Intrustion_Analyst_FINAL.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572322/Cyber_Intrusion_Analyst_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:55.720' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (80, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/510127/Standard_Data_Analyst.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572323/Data_Analyst_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:56.077' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (81, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/510149/Standard_Unified_Communications_Trouble_Shooter.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572328/Unified_Communications_Trouble_Shooter_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:57.033' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (82, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/576276/Infrastructure_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/576277/Assessment_Plan_Infrastucture_Technician.pdf', CAST(N'2017-10-10T14:36:57.867' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (83, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411710/MANAGEMENT_CONSULTANCY_-_Junior_Management_Consultant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514167/Junior_Management_Consultant_Assessment_Plan.pdf', CAST(N'2017-10-10T14:36:58.153' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (84, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455217/VISUAL_EFFECTS_Junior_2D_Artist_Standard__Visual_Effects_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514587/VFX_Junior_2D_Artist_Assessment__Plan.pdf', CAST(N'2017-10-10T14:36:58.523' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (85, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455216/VISUAL_EFFECTS_Assistant_Technical_Director.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514578/VFX_Assistant_Technical_Director_Assessment.pdf', CAST(N'2017-10-10T14:36:58.883' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (86, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555628/Aviation_ground_specialist_level_3_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555629/Aviation_ground_specialist_assessment_plan.pdf', CAST(N'2017-10-10T14:36:59.243' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (87, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555630/Aviation_ground_operator_level_2_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555631/Aviation_ground_operative_assessment_plan.pdf', CAST(N'2017-10-10T14:36:59.613' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (88, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499756/Rail_Engineering_Advanced_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648836/ST0316_Rail_Engineering_Advanced_Technician_L4_Assessment_Plan_29.09.17.pdf', CAST(N'2017-10-10T14:37:00.700' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (89, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499757/Rail_Engineering_Technican.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648844/ST0318_Rail_Engineering_Technician_L3_Assessment_Plan_29.09.17.pdf', CAST(N'2017-10-10T14:37:01.953' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (90, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/506513/Rail_Engineering_Operative.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/648841/ST0317_Rail_Engineering_Operative_L2_Assessment_Plan_29.09.17.pdf', CAST(N'2017-10-10T14:37:02.287' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (91, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/517843/STANDARD_Software_Tester__002_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572319/Software_Tester_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:02.660' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (92, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411718/ENGINEERING__DESGIN___DRAUGHTING_-_Engineering_Design___Draughtsperson.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/649218/Engineering_Design_and_Draughtsperson_ST0164_AP_for_publishing__03.1017.pdf', CAST(N'2017-10-10T14:37:03.040' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (93, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411899/HOSPITALITY_-_Commis_Chef.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/538469/Commis_Chef_Apprenticeship_Assessment_plan.pdf', CAST(N'2017-10-10T14:37:04.323' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (94, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455218/WELDING_L2.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/519998/Assessment_Plan_Welder_Level_2.pdf', CAST(N'2017-10-10T14:37:05.393' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (95, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455219/WELDING_L3.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/520000/Assessment_Plan_Welder_Level_3.pdf', CAST(N'2017-10-10T14:37:06.677' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (96, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499730/Hospitality_Team_Member_Apprenticeship_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/524908/Hospitality_team_member_assessment_plan.pdf', CAST(N'2017-10-10T14:37:07.050' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (98, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/522676/Cyber_Security_Technologist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572329/Cyber_Security_Technologist_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:07.400' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (99, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/470806/HEALTHCARE_Healthcare_Science_Assistant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/522660/HCSA_assessment_plan.pdf', CAST(N'2017-10-10T14:37:08.613' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (100, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411740/TRANSPORT_-_Transport_Planning_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/522659/Transport_Planning_Technician_Apprenticeship_-_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:09.970' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (101, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384233/RETAIL_-_Retailer_standard_-_Final_081214.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/589276/Retailer_assessment_plan.pdf', CAST(N'2017-10-10T14:37:10.853' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (102, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411716/HEALTHCARE_-_Healthcare_Assistant_Practitioner.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564297/Assistant_Practitioner_Health_Assessment.pdf', CAST(N'2017-10-10T14:37:11.233' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (103, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411717/HEALTHCARE_-_Healthcare_Support_Worker.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564294/Healthcare_Support_Worker_Assessment.pdf', CAST(N'2017-10-10T14:37:12.673' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (104, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/549192/Operations_Departmental_Manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574284/Operations_Departmental_Manager_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:13.723' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 105, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/526930/Team_Leader_Supervisor.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/526962/Team_Leader_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:14.653' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 106, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455211/PAPERMAKING_Papermaker.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/526940/Papermaking_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:14.983' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 107, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/551142/Embedded_Electronic_Systems_Design_and_Development_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528668/Embedded_Electronic_Systems_Design_and_Development_Engineer_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:15.987' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 108, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/487589/HM_ARMED_FORCES_-_HM_Forces_Serviceperson__Public_Services_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528676/HM_Services_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:16.830' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 109, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/526941/LOGISTICS_AND_SUPPLY_CHAIN_Supply_Chain_Operator.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/532318/Supply_Chain_Operator_270616_v1_AP.pdf', CAST(N'2017-10-10T14:37:17.857' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 110, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/493607/LGV_Driver.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/616433/Large_Goods_Vehicle__LGV__Driver_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:18.210' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 111, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/526947/Supply_Chain_Warehouse_Operative_standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/532326/Warehouse_Operative_270616_v1_standard.pdf', CAST(N'2017-10-10T14:37:19.200' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 112, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/470012/TV_PRODUCATION_AND_BROADCASTING_Broadcast_Production_Assistant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/532328/Broadcast_Production_Assistant_270616_v1_AP.pdf', CAST(N'2017-10-10T14:37:19.543' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES ( 114, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/576808/Aircraft_Maintenance_Certifying_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/534101/Assessment_Plan_for_Aircraft_Maint_Cert_Eng.pdf', CAST(N'2017-10-10T14:37:21.023' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (116, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499761/Survival_Equipment_Fitter.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/535995/Survival_Equipment_Fitter_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:21.363' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (117, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/638846/ACCOUNTANCY_-_Professional_AccountingTax_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/539995/Professional_Accounting_Taxation_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:21.783' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (118, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384215/ADULT_SOCIAL_CARE_-_Lead_Adult_Care_Worker_L3_standard_-_FINAL.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/539996/Lead_ACW_Assessment_plan.pdf', CAST(N'2017-10-10T14:37:23.227' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (119, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384256/ADULT_SOCIAL_CARE_-_Adult_Care_Worker_L2_standard_-_FINAL.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/539997/ACW_Assessment_plan.pdf', CAST(N'2017-10-10T14:37:23.987' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (120, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384213/TRAVEL_-_Travel_consultant_standard_-_Final_081214.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/540398/Travel_consultant_standard_assessment_plan_v2.pdf', CAST(N'2017-10-10T14:37:24.300' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (121, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/371914/AVIATION_Airside_Operator.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/542556/Airside_operator_standard_assessment_plan.pdf', CAST(N'2017-10-10T14:37:24.680' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (122, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455236/CUSTOMER_SERVICE_Customer_Service_Practitioner.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/584774/Assessment_Plan_Customer_Service_Practitioner_17_01_17.pdf', CAST(N'2017-10-10T14:37:25.037' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (123, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455226/AVIATION_Aviation_Operations_Manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546990/Aviation_operator_manager_standard_assessment_plan.pdf', CAST(N'2017-10-10T14:37:25.413' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (124, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372109/CONSTRUCTION_Highways_Electrical_Services_Operative.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546985/Assessment_Plan_Highway_Electrician-Service_Operative_Level_3.pdf', CAST(N'2017-10-10T14:37:26.613' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (125, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/384271/CONSTRUCTIONBB_-_Highways_Electrical-MaintenanceAndInstallationOperativeL2_-_Final.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546983/Assessment_Plan_Highway_Electrical_Maintenance_And_Installation_Operative.pdf', CAST(N'2017-10-10T14:37:26.943' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (126, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/454982/FIRE_EMERGENCY_AND_SECURITY_SYSTEMS_Fire_Emergency_and_Security_Systems_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546982/Fire_Emergency_and_Security_Systems_assessment_plan.pdf', CAST(N'2017-10-10T14:37:28.463' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (127, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546974/Electrical_Power_Protection_and_Plant_Commissioning_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/558566/EPPPCE-AssessmentPlan-Sept16-V2.pdf', CAST(N'2017-10-10T14:37:29.513' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (128, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/536030/Associate_Project_manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546981/PM_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:30.853' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (129, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555635/Food_and_Drink_Advanced_Process_Operator_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/621189/Food_and_Drink__Advanced_Operators_EPA.pdf', CAST(N'2017-10-10T14:37:31.780' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (130, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555634/Food_and_Drink_Process_Operator_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/548441/Food_and_Drink_Operators__Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:32.767' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (131, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/612597/Standard_for_Food_Technologist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/548473/Food_Technologist_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:33.117' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (132, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499821/NDT_Operator.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/547176/Assessment_Plan_-_NDT_Operator_.pdf', CAST(N'2017-10-10T14:37:33.483' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (133, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/517363/Assistant_Accountant_Apprenticeship_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/589404/Assistant_Accountant_Assessment_plan.pdf', CAST(N'2017-10-10T14:37:33.840' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (134, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455231/BUS__COACH___HGV_Bus_and_Coach_Engineering_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/550975/Assessment_Plan_bus_and_coach_engineering_technician.pdf', CAST(N'2017-10-10T14:37:34.203' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (135, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455232/BUS__COACH___HGV_Heavy_Vehicle_Service_and_Maintenance_Technician_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/550973/Assessment_Plan_heavy_vehicle_service_and_maintenance_technician.pdf', CAST(N'2017-10-10T14:37:35.580' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (136, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/454764/BUS__COACH___HGV_Bus_Coach_Engineering_Manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/550984/Assessment_Plan_bus_and_coach_engineering_manager.pdf', CAST(N'2017-10-10T14:37:36.773' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (137, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/546971/Furniture_Manufacturer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/551126/Furniture_Man_AP.pdf', CAST(N'2017-10-10T14:37:37.087' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (138, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411921/HOSPITALITY_-_Hospitality_Supervisor.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/551129/Hospitality_supervisor_assessment_plan.pdf', CAST(N'2017-10-10T14:37:37.457' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (139, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372243/HOSPITALITY_Senior_Chef_-_Production_Cooking.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553037/Senior_chef_production_cooking_assessment_plan.pdf', CAST(N'2017-10-10T14:37:38.913' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (140, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411512/RETAIL_-_Retail_Team_Leader.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/551139/Retail_team_leader_assessment_plan.pdf', CAST(N'2017-10-10T14:37:39.260' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (141, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499751/Aviation_Maintenance_Mechanic__Military_.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553788/Aviation_Maintenace_Mechanic_Military_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:39.590' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (142, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553847/Standard_IT_Technical_Sales.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572331/IT_Technical_Salesperson_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:39.983' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (143, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598456/Compliance_Risk_Officer_Post_Panel.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598457/Compliance_Risk_Officer_assessment_plan.pdf', CAST(N'2017-10-10T14:37:40.337' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (144, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598445/Senior_Compliance_Risk_Specialist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598447/Senior_Compliance_Risk_Specialist__assessment_plan.pdf', CAST(N'2017-10-10T14:37:40.687' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (145, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455072/GROUNDSMANSHIP_Sports_Turf_Operative.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/553786/Assessment_Plan_Sports_Turf_Operative.pdf', CAST(N'2017-10-10T14:37:41.740' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (146, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592680/MOET_standard-V3.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592681/Maintenance__Operations_Engineering_Technician_Assessment_Plan-V2.pdf', CAST(N'2017-10-10T14:37:42.097' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (147, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411497/RETAIL__-_Retail_Manager.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564285/Retail_manager_assessment_plan.pdf', CAST(N'2017-10-10T14:37:43.320' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (148, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598451/Advanced_Credit_Controller_Debt_Collection_Specialist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598453/Adv_Cred_Controlr__Debt_Collecn_Specialist_assessment_plan.pdf', CAST(N'2017-10-10T14:37:43.753' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (149, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564283/AdvancedDairyTechnologistStandard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564284/Advanced_Dairy_Technology-Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:44.120' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (150, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/522687/Health_Care_Science_Associate.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564288/HCS_Associate_EPA_Plan.pdf', CAST(N'2017-10-10T14:37:44.490' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (151, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603416/Senior_Healthcare_Support_Worker_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/608816/Senior_Healthcare_Support_Worker_assessment_plan.pdf', CAST(N'2017-10-10T14:37:44.827' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (152, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/565708/Advanced_Butcher_Standard_-_ST0077.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/565707/AdvancedButcheryAessessment_Plan.pdf', CAST(N'2017-10-10T14:37:46.127' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (153, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572989/Financial_Adviser_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572990/Financial_Adviser_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:46.487' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (154, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/549726/Software_Development_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578747/Software_Development_Technician_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:46.897' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (155, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/549743/Unified_Communications_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578751/Unified_Communications_Techncian_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:48.170' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (156, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/455222/AMBULANCE_SERVICES_Associate_Ambulance_Practitioner.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/583802/Associate_Ambulance_Practitioner_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:48.527' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (157, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/580178/Hair_Professional_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/580177/Hair_prof_assessment_plan.pdf', CAST(N'2017-10-10T14:37:49.880' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (158, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/548747/Spectacle_Maker_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/580171/Spectacle_Maker.pdf', CAST(N'2017-10-10T14:37:50.210' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (159, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/503649/Event_Assistant.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/583797/Event_Assistant_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:50.573' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (160, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411721/COMPOSITES_-_Composites_Technician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592446/Composites_technician_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:50.930' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (161, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/593962/Power_Engineer_Integrated_Degree_Apprenticeship.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/593963/Power_Engineer_Integrated_Degree_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:51.290' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (162, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411803/FACILITIES_MANAGEMENT_-_Facilities_Management_Supervisor.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592720/FM_Supervisor_Assessment_Plan_final.pdf', CAST(N'2017-10-10T14:37:52.410' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (163, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603423/Nuclear_Technician_Apprenticeship_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603424/Nuclear_Technician_EPA_Plan.pdf', CAST(N'2017-10-10T14:37:52.733' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (164, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555636/BSE_Installer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/603427/BSE_INSTALLER_AP.pdf', CAST(N'2017-10-10T14:37:53.083' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (165, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605494/Standard_IS_Business_Analyst.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605495/Assessment_Plan_IS_Business_Analyst.pdf', CAST(N'2017-10-10T14:37:53.430' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (166, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605489/Level_7_Standard_-_Post_Graduate_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605492/Post_Graduate_Engineer_End_Point_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:54.687' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (167, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605484/Level_3_Engineering_Technician_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605485/Engineering_Technician_End_Point_Assessment_Plan.pdf', CAST(N'2017-10-10T14:37:55.627' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (168, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/586614/Apprenticeship_Standard_L6_Healthcare_Science_Practitioner.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/605493/Health_Care_Science_Practitioners_EPA.pdf', CAST(N'2017-10-10T14:37:55.953' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (169, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411888/HOSPITALITY_-_Chef_de_Partie.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/607482/Chef_de_Partie_assessment_plan.pdf', CAST(N'2017-10-10T14:37:56.340' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (1, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/499736/Standard_Network_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/572314/Network_Engineer_Assessment_Plan.pdf', CAST(N'2017-10-11T08:35:49.253' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (2, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/624040/Standard_Software_Developer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/578776/Software_Developer.pdf', CAST(N'2017-10-18T14:04:06.370' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (5, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448907/ELECTROTECHNICAL_Installation_Electrician__Maintenance_Electrician.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/459797/Electrotechnical.pdf', CAST(N'2017-10-18T14:04:06.440' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (6, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448908/ENERGY___UTILITIES_Power_Network_Craftsperson.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/574230/Power_Network_Craftsperson_V3.pdf', CAST(N'2017-10-18T14:04:06.813' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (7, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/598463/Financial_Services_Relationship_Mgr_Banking.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/528460/Relationship_Manager_Assessment_Plan.pdf', CAST(N'2017-10-18T14:04:06.933' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (92, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/411718/ENGINEERING__DESGIN___DRAUGHTING_-_Engineering_Design___Draughtsperson.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/652896/ST0164_Engineering_Design_and_Draughtsperson_L3_EQA_Update_for_Publicati.._.pdf', CAST(N'2017-10-23T08:41:54.290' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (20, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592663/Dental_Practice_Manager_Standard_-_Feb_2017.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/592664/Dental_Practice_Manager_Assessment_Plan.pdf', CAST(N'2017-10-25T10:43:34.303' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (23, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/372239/PROPERTY_SERVICES_Property_Maintenance_Operative.ashx.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/416546/Assessment_Plan_-_Property_Maintenance_Operative_Final_Version.pdf', CAST(N'2017-10-25T10:43:34.527' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (149, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/564283/AdvancedDairyTechnologistStandard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655691/ST0393_Advanced_Dairy_Technology_L5_AP_for_Publication_EQA_Updated_Oct_2....pdf', CAST(N'2017-10-30T11:53:45.207' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (16, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555632/Food_and_Drink_Maintenance_Engineer.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655690/ST0195_Food_and_Drink_Maintenance_Engineer_L3_AP_for_Publication_EQA_Upd....pdf', CAST(N'2017-10-30T12:32:17.100' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (52, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/448905/DEFENCE_Systems_Engineering_Master_Level.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655678/ST0107_Systems_Engineering_L7_AP_for_Publication_EQA_Updated_Oct_2017.pdf', CAST(N'2017-10-30T12:32:57.060' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (129, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555635/Food_and_Drink_Advanced_Process_Operator_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655684/ST0196_Food_and_Drink_Advanced_Process_Operator_L3_AP_for_Publication_EQ....pdf', CAST(N'2017-10-30T12:34:18.553' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (130, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/555634/Food_and_Drink_Process_Operator_Standard.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655679/ST0199_Food_and_Drink_Process_Operator_L2_AP_for_Publication_EQA_Updated....pdf', CAST(N'2017-10-30T12:34:19.573' AS DateTime))
GO
INSERT [dbo].[PdfTable] ([StandardCode], [StandardUrl], [AssessmentUrl], [DateSeen]) VALUES (131, N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/612597/Standard_for_Food_Technologist.pdf', N'https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/655681/ST0198_Food_Technologist_L3_AP_for_Publication_EQA_Updated_Oct_2017.pdf', CAST(N'2017-10-30T12:34:20.637' AS DateTime))
